export const LOAD_PROFILES = 'LOAD_PROFILES';
export const LOAD_PROFILE = 'LOAD_PROFILE';
export const PROFILES_LOADED = 'PROFILES_LOADED';
export const PROFILE_LOADED = 'PROFILE_LOADED';

export const EMPTY_PROFILE = 'EMPTY_PROFILE';
